# Puerto y contexto
server.port=8080
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Destino y remitente del correo
app.mail.to=alberto.morales@dpr.icu
app.mail.from=leonardo.esteban@dpr.icu

# Configuracion SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leonardo.esteban@dpr.icu
spring.mail.password=invk hile mrye tvsb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging basico
logging.level.org.springframework.mail=INFO
logging.level.org.Reunion=INFO
