# Puerto y contexto
server.port=8080

# Destino y remitente del correo
app.mail.to=alberto.morales@dpr.icu
app.mail.from=no-reply@example.com

# Configuracion SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=8c6a637ed72252
spring.mail.password=9a7757a2aa3a2a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging basico
logging.level.org.springframework.mail=INFO
logging.level.org.example=INFO
